config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  #Edit some of devise's functionality. Devise will know if it's a basic or pro user
  devise_for :users, controllers: { registrations: 'users/registrations'}
  
  # Nested routes. Each of our users will have profile resource
  # :user_id in routes refers to the actual id value in the database
  resources :users do
    #singular because a user only has one profile
    resource :profile
  end
  
  get 'about', to: 'pages#about'
  
  # resources will have rails create 7 different routes, but we only need
  # two. new and create. GET and POST in HTTP verb
  resources :contacts, only: :create
  
  # makes custom URL. contact/new changes to contact-us. Whenver rails gets a get request for /contact-us,
  # rails knows to run the contacts controller new action. This gives us new/GET
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end    

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
   
   # Checks if the person browsing site is logged in. If they aren't, none of these profile
   # related actions will run.
   before_action :authenticate_user!      #, only: [:new, :edit]  you can specify certain actions
   
   # Makes it so users can only edit their own profile page. Function defined below.
   before_action :only_current_user
   
   # GET to /users/:user_id/profile/new
   def new
      # Render blank profile details form. Create a new profile object to be used in form.html.erb
      @profile = Profile.new
   end
   
   # POST to /users/:user_id/profile
   def create
      # Grab user_id from params Ensure that we have the user that is filling out the form
      @user = User.find( params[:user_id] )
      # Build a profile in the machines memory using the whitelisted profile fields
      # Create profile linked to this specific user. Build function provided by rails
      # with this kind of association. Kind of like .new, but prefills foreign key.       images.build plural/has many relationship
      @profile = @user.build_profile( profile_params )
      
      if @profile.save
         flash[:success] = "Profile updated!"
         # Redirects to user profile once they submit their information.
         # Needs to inject the user id into the URL path.
         redirect_to user_path(id: params[:user_id])
      else
         render action: :new
      end
   end   
   
   # GET to /users/:user_id/profile/edit
   def edit
      # @profile sent to _form.html.erb will already be filled out. Form on that page will be for
      # a user that is already filled out
      @user = User.find( params[:user_id] )
      @profile = @user.profile 
   end
   
   # PUT to /users/:user_id/profile. Rails knows that the user came to form from the edit action
   # vs the new action. Injects hidden form into edit profile form with value of patch.
   def update
      # Retrieve the user from the database
      @user = User.find( params[:user_id] )
      # Retrieve user's profile
      @profile = @user.profile
      # Mass assign edited profile attributes and save (update)
      if @profile.update_attributes(profile_params)
         flash[:success] = "Profile updated!"
         # Redirect user to their profile page
         redirect_to user_path(id: params[:user_id] )
      # reload the edit action so user can try to edit page again
      else
         render action: :edit
      end
   end   
   
   private
      def profile_params
         params.require(:profile).permit(:first_name, :last_name, :job_title, :avatar, :phone_number, :contact_email, :description)
      end
      
      # Set @user to the id of the current user logged in. If the id does NOT match the id
      # part of the URL they are trying to edit, then redirect them to the home page
      def only_current_user
         @user = User.find( params[:user_id] )
         redirect_to(root_url) unless @user == current_user
      end
end

app/views/profiles/_form.html.erb
<!-- Create of edit a profile related to the user that is signing up/logged in. Related to profiles_controller.
for new, @profile in new action. Edit in edit action. In profiles_controller
URL specified because it is nested.       :multipart needs to be there for image upload-->
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
   <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
   </div>
   
   <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
   </div>
   
   <!-- Image upload. :avatar whitelisted in profiles_controller file -->
   <div class="form-group">
      <%= f.label :avatar %>
      <%= f.file_field :avatar, class: 'form-control' %>
   </div>
   
   <!-- Drop down menu -->
   <div class="form-group">
      <%= f.label :job_title %>
      <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
   </div>
   
   <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>
   </div>
   
   <div class="form-group">
      <%= f.label :contact_email %>
      <%= f.text_field :contact_email, class: 'form-control' %>
   </div>
   
   <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
   </div>
   
   <div class="form-group">
      <%= f.submit "Update Profile", class: 'btn btn-primary' %>
   </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <h1 class="text-center">Edit Your Profile</h1>
         <p class="text-center">Be a part of the DevMatch community and fill out your profile!</p>
         <div class="well">
            <!-- Pull in partial html file 'form' -->
            <%= render 'form'%>
         </div>
      </div>
   </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <h1 class="text-center">Create Your Profile</h1>
         <p class="text-center">Be a part of the DevMatch community and fill out your profile!</p>
         <div class="well">
            <!-- Pull in partial html file 'form' -->
            <%= render 'form'%>
         </div>
      </div>
   </div>
</div>