config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  #Edit some of devise's functionality. Devise will know if it's a basic or pro user
  devise_for :users, controllers: { registrations: 'users/registrations'}
  
  # Nested routes. Each of our users will have profile resource
  # :user_id in routes refers to the actual id value in the database
  resources :users do
    #singular because a user only has one profile
    resource :profile
  end
  
  get 'about', to: 'pages#about'
  
  # resources will have rails create 7 different routes, but we only need
  # two. new and create. GET and POST in HTTP verb
  resources :contacts, only: :create
  
  # makes custom URL. contact/new changes to contact-us. Whenver rails gets a get request for /contact-us,
  # rails knows to run the contacts controller new action. This gives us new/GET
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/pages/about.html.erb
<div class="container text-center">
  <h1>About Us</h1>
  <p>We are DevMatch. Our company focuses on creating an exclusive community for
  developers, investors, and entrepreneurs to meet.</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
   <h1 class="dummy">Do NOT use real information. Dummy website. </h1>
   <h1>Welcome to DevMatch</h1>
   <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>

<div class="container home-signup-links">
   <div class="row">
      <!-- Check if user is signed in. If signed in, check if profile has been created.
      If so, put links to edit or view profile. If not, link to create profile.
      If not signed in, showshow sign up forms. Also display button to community regardless. -->
      <% if user_signed_in? %>
         <div class="col-md-6">
            <div class="well">
               
               <h2 class="text-center">Your Profile</h2>
               <% if current_user.profile %>
                  <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
                  <%= link_to "View your profile", user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
               <% else %>
                  <p class="text-center">Create your profile so that you can share your information with the community</p>
                  <!-- Pass the current user id into the URL to make it dynamic. -->
                  <%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
               <% end %>
               
            </div>
         </div>
         
         <div class="col-md-6">
            <div class="well">
               <h2 class="text-center">The Community</h2>
               <p class="text-center">Visit the community to meet other developers, entrepreneurs, and investors!</p>
               <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
            </div>
         </div>
         
      <% else %>
         <div class="col-md-6">
            <div class="well">
               <h2 class="text-center">Basic Membership</h2>
               <h4>Sign up for free and get basic access to the community.</h4>
               <br>
               <!-- (plan: @basic_plan.id) passes information through URL. Similar for pro_plan.
               Will be used in a conditional statement to display appropriate sign up form on new.html.erb.
               Instance variable defined in pages_controller file-->
               <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: "btn btn-primary btn-lg btn-block" %>
            </div>
         </div>
         
         <div class="col-md-6">
            <div class="well">
               <h2 class="text-center">Pro Membership</h2>
               <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
               <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: "btn btn-success btn-lg btn-block" %>
            </div>
         </div>
      <% end %>
   </div>
</div>