config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  #Edit some of devise's functionality. Devise will know if it's a basic or pro user
  devise_for :users, controllers: { registrations: 'users/registrations'}
  
  # Nested routes. Each of our users will have profile resource
  # :user_id in routes refers to the actual id value in the database
  resources :users do
    #singular because a user only has one profile
    resource :profile
  end
  
  get 'about', to: 'pages#about'
  
  # resources will have rails create 7 different routes, but we only need
  # two. new and create. GET and POST in HTTP verb
  resources :contacts, only: :create
  
  # makes custom URL. contact/new changes to contact-us. Whenver rails gets a get request for /contact-us,
  # rails knows to run the contacts controller new action. This gives us new/GET
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            DevMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <!-- HTML way to add naviagation buttons
              <a href="/users/sign_in" class="btn btn-default navbar-btn">Log In</a>
              <a href="/users/sign_up" class="btn btn-default navbar-btn">Sign Up</a>
            -->
            
            <!-- user_signed_in? comes from Devise. Get rid of Log In and Sign Up buttons if logged in -->
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn"%>
            <% end %>
            
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Community", users_path %></li>
              <!-- In Devise folder under views -->
              <li><%= link_to "My Account", edit_user_registration_path %></li>
            <% end %>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <!-- Displays flash notice from contacts_controller file. 
    Dynamically creates CSS depending on which flash key value comes through
    Placed in this file incase you want to redirect anywhere else on website. Will still display-->
    <div class="container flash-container">
      <% flash.each do |type, msg| %>       <!-- |key, value| of flash hash. Will be one key-value pair -->
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <%= yield %>
    
  </body>
</html>